<div class="page-content">
    <div class="page-title">
        <div class="sub"><?php echo _t("About")?></div>
        <div class="main"><?php echo _t("Dr Kwak")?></div>
    </div>
    <div class="detail-content">     
	    <div style="margin:-5px 0 10px 10px;position: relative;cursor:pointer;">
            <a href="http://www.youtube.com/watch?v=WsxlGwxFa48" rel="prettyPhoto">
            <div style="position: absolute;left:217px;top:110px;">
                <img width="120" alt="Welcome to Kwak Family Medicine video" src="/images/play_movie_icon.png"/>
            </div>
		    <img width="537" alt="Welcome to Kwak Family Medicine video" src="/images/a_talk_with_dr_kwak.jpg"/>
            </a>		
	    </div>
	    <?php echo $this->body; ?>
    </div>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto();
    });
</script>