<div class="page-content">
    <div class="page-title">
        <div class="sub"><?php echo _t("What about")?></div>
        <div class="main"><?php echo _t("insurance?")?></div>
        </div>                    
    <div class="detail-content-contact">                        
        <div>    
		    <?php echo $this->body; ?>            
            <p>
	            &nbsp;</p>
	
	    </div>
    </div>          
</div>
