<div class="page-content">                   
    <div class="detail-content-index">                        
        <div style="padding: 30px 0;">
            	    
    <div style="text-align: center; vertical-align: middle;" class="login-cont">
		<form method="post" action="/index/login" name="login_form" id="login_form" class="login-block">
			<div class="login-title">Login</div>
			<div id="login_message_id" class="login-messages"><?= _t($this->message)?></div>
			<label>Username:</label> <input type="text" name="username"><br>					
			<label>Password:</label> <input type="password" name="password"><br><br>
			<label> </label><input type="submit" value="Login" style="width:50px;">&nbsp;&nbsp; <input type="reset" value="Reset" style="width:50px;">
			<br>
			<label> </label>
		</form>
	</div>        
        
        </div>
    </div>          
</div>