<div class="left-content">
	<div class="news-header"><h1><?php echo _t("LBL_MENU_News");?></h1></div>
	<div class="page-content">
		<div class="all-news">
			<div class="list-news">
				<?php echo $this->htmlResult;?>
				<!-- 
				<ul>
					<li><a href="">New patients are welcomed and accepted.</a> <span class="news-date">(22/12/2010 17:12)</span> <img src="/images/new.gif" style="padding: 0pt; float: none;"></li>
					<li><a href="">Join KFM on facebook and twitter</a> <span class="news-date">(22/12/2010 17:12)</span></li>
					<li><span class="news-title-text">100th and 1000th patient to join the practice will win a special prize.</span> <span class="news-date">(22/12/2010 17:12)</span></li>
				</ul>
				 -->
			</div>
		</div>
	</div>
</div>