<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="<?php echo $this->keyword?>"/>
    <meta name="description" content="<?php echo $this->description;?>"/>
    <meta name="viewport" content="width=1130" />
    <title><?php echo ($this->title? $this->title : "Kwak Family Medicine, PC"); ?></title>
    <?php echo $this->headLink()->appendStylesheet('/css/style.css?20140531') ?>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <script type="text/javascript" src="/js/common.js?20110405"></script>
    <script src="/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="/css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
    <script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-21819218-1']);
	  _gaq.push(['_setDomainName', '.kwakfamilymedicine.com']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
    <script>
        $(document).ready(function () {
            var changeBgImage = function () {
				if ( $.browser.mozilla == true) {
					$("#top-bg").css("width", "1130px");
					$("#top-bg").css("left", $("#header-logo").offset().left);
				}else{
					if ($(window).width() > 1420) {
						var zoom = $(window).width() / 1420;
						console.log(zoom);
						$("#top-bg").css("zoom", zoom);					
						//$("#top-bg").css("width", $(window).width() + 'px');
					} else {
						$("#top-bg").css("zoom", 1);
						$("#top-bg").css("width", $(window).width() + 'px');
					}
				}
            };
            $("#top-bg").show();
            changeBgImage();
            $(window).resize(function () {
                changeBgImage();
            });
        });
   </script>
  </head>
  <body>
    <div id="top-bg">
    </div>
    <div class="page-margin">
		<div class="header">
			<div class="header-logo left" id="header-logo">
				<a href="/index"><img src="/images/logo.png" alt="Kwak Family Medicine FC" border="0"/></a>
			</div>
            <div class="social-connect right">                
				<a target="facebook" href="http://www.facebook.com/pages/Kwak-Family-Medicine-PC/158413460880351"><img src="/images/icon_fb.png" border="0" alt="Facebook"></a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a target="twitter" href="http://twitter.com/jameskwakmd"><img src="/images/icon_twitter.png" border="0" alt="Twitter"></a>				
            </div>
		</div>
        <div class="clr"></div>
        <div class="left-content">
            <div class="nav-bar">
                <ul>
                    <li<?php echo ($this->action == 'index'  && $this->controller == 'index' ? ' class="current"' : '') ?>><div><a href="/index"><?php echo _t("LBL_MENU_Home");?></a></div></li>
					<li<?php echo ($this->action == 'about' ? ' class="current"' : '') ?>><div><a href="/index/about"><?php echo _t("LBL_MENU_About Dr. Kwak");?></a></div></li>
					<li<?php echo ($this->action == 'staff' ? ' class="current"' : '') ?>><div><a href="/index/staff"><?php echo _t("LBL_MENU_Staff");?></a></div></li>
					<li<?php echo ($this->action == 'location' ? ' class="current"' : '') ?>><div><a href="/index/location"><?php echo _t("LBL_MENU_Location and hours");?></a></div></li>
					<li<?php echo ($this->action == 'contact' ? ' class="current"' : '') ?>><div><a href="/index/contact"><?php echo _t("LBL_MENU_Contact us");?></a></div></li>
					<li<?php echo ($this->action == 'faq' ? ' class="current"' : '') ?>><div><a href="/index/faq"><?php echo _t("LBL_MENU_FAQ");?></a></div></li>
					<li<?php echo ($this->action == 'insurance' ? ' class="current"' : '') ?>><div><a href="/index/insurance"><?php echo _t("LBL_MENU_Insurance");?></a></div></li>
					<li<?php echo ($this->action == 'news' ? ' class="current"' : '') ?>><div><a href="/index/news"><?php echo _t("LBL_MENU_News");?></a></div></li>
					<li<?php echo ($this->action == 'links' ? ' class="current"' : '') ?>><div><a href="/index/links"><?php echo _t("LBL_MENU_Links");?></a></div></li>
					<li<?php echo ($this->action == 'forms' ? ' class="current"' : '') ?>><div><a href="/index/forms"><?php echo _t("LBL_MENU_Forms");?></a></div></li>
                    <li<?php echo ($this->action == 'newsletters' ? ' class="current"' : '') ?>><div><a href="/index/newsletters"><?php echo _t("LBL_MENU_Newsletters");?></a></div></li>
                    <li><div>
                        <a href="https://my.patientfusion.com/"><?php echo _t("LBL_MENU_My Patient Page");?></a>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="clr"></div>

            <?php if (VNMLS_Model_Table_Users::getCurrentUserID()){ ?>
				<div class="admin-menu-container">
					<div class="title">
						Admin menu
					</div>
					<div>
						<ul>
							<li>
								<a href="/node/?type=news">News Management</a>
							</li>
							<li>
								<a href="/node/?type=page">Pages Management</a>
							</li>
							<li>
								<a href="/node/?type=testimonial">Testimonials Management</a>
							</li>
                            <li>
								<a href="/node/?type=faq">Faq Management</a>
							</li>
							<li>
								<a href="/node/?type=label">Label Management</a>
							</li>
							<li>
								<a href="/node/?type=link">Link Management</a>
							</li>
							<li>
								<a href="/node/?type=block">Blocks Management</a>
							</li>
							<li>
								<a href="/index/logout">Logout</a>
							</li>
						</ul>
					</div>
				</div>
				<?php } ?>
            <?php echo getBlockContent(5);?>
            <div class="core-value-box">
                <div class='sprite typo_1'></div>
            </div>
        </div>
        <div class="right-content">
            <div class="banner-container">
                <div class="language-bar">
                    <ul id="container-language">
                        <li><a href="http://new.kwakfamilymedicine.com/" alt="English" title="English" style="font-weight:bold">English</a></li>
                        <li><a href="http://krnew.kwakfamilymedicine.com/" alt="한국어" title="한국어">한국어</a></li>
                        <li class="last"><a href="#" onmouseover="mopen('m1')" onmouseout="mclosetime()">All Languages</a>
                        	<div id="m1" onmouseover="mcancelclosetime()" onmouseout="mclosetime()" style="visibility: hidden;">
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Cfr&amp;hl=en&amp;ie=UTF8" target="_blank">Français</a>
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Ces&amp;hl=en&amp;ie=UTF8" target="_blank">Español</a>
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Cpt&amp;hl=en&amp;ie=UTF8" target="_blank">Português</a>
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Cja&amp;hl=en&amp;ie=UTF8" target="_blank">日本語</a>
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Czh_tw&amp;hl=en&amp;ie=UTF8" target="_blank">中文</a>
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Cde&amp;hl=en&amp;ie=UTF8" target="_blank">Deutsch</a>
					        <a href="http://www.google.com/translate?u=http%3A%2F%2Fkwakfamilymedicine.com%2F&amp;langpair=en%7Cvi&amp;hl=en&amp;ie=UTF8" target="_blank">Tiếng Việt</a>
					        </div>
                        </li>
                 </ul>
                </div>
                <div class="banner-image <?= ($this->controller != 'index') ? 'index' : $this->action ?>-banner">
                    <div class="banne-slogan">
                        <div><?php echo _t("LBL_Where Your Family’s Health Is Protected");?></div>
                    </div>
                </div>
            </div>
            <div class="main-container">
                <?php echo $this->layout()->content ?>                
               <?php if ($this->controller == 'index'){ ?>
                <div class="page-content-right">
                <div class="testimonials-container">
                    <div class="title">
                        What our patients say?
                    </div>
                    <div id="testo-list">
                    <div class="testo-detail">
                        <div class="testo-logo">
                            <span class='sprite testi_1 left'></span>
                        </div>
                        <div class="testo-content">
                            <div class="testo-name"><?= $this->testimonials[0]['name']?></div>
                            <div class="testo-text">
                                “<?= $this->testimonials[0]['text']?>”
                            </div>                        
                        </div>
                    </div>
                    <div id="testo-break">
                        <div class="clr"></div>
                        <div class="testo-break-line"></div>
                    </div>
                    <div class="testo-detail" id="testo-detail2">
                        <div class="testo-logo">
                            <span class='sprite testi_2 left'></span>
                        </div>
                        <div class="testo-content">
                            <div class="testo-name"><?= $this->testimonials[1]['name']?></div>
                            <div class="testo-text">
                                “<?= $this->testimonials[1]['text']?>”
                            </div>
                        </div>
                    </div>
                    </div>
                    <div class="testo-more">
                        Read more <span id="testo_more_next" class="sprite icon_next right"></span> <span id="testo_more_back" class="sprite icon_back right"></span>
                    </div>
                </div>
                <div class="clr"></div>
                <div class="facebook-plugin-block">
					<div class="title"> Find us on Facebook </div>
					<div class="home-contant-content">
					    <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fpages%2FKwak-Family-Medicine-PC%2F158413460880351&amp;width=290&amp;colorscheme=light&amp;show_faces=true&amp;stream=false&amp;header=false&amp;height=262" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:290px; height:262px;" allowTransparency="true"></iframe>
					</div>
				</div>
                </div>
              <?php } ?>                    
            </div>

        </div>
	</div>
    <div class="clr"></div>
	<div style="margin-top: 15px;background: #2d78d3;width: 100%;">
        <div class="page-margin">
            <div class="foot-nav">
                <ul>
                    <li<?php echo ($this->action == 'index'  && $this->controller == 'index' ? ' class="current"' : '') ?>><a href="/index"><?php echo _t("LBL_MENU_Home");?></a></li>
					<li<?php echo ($this->action == 'about' ? ' class="current"' : '') ?>><a href="/index/about"><?php echo _t("LBL_MENU_About Dr. Kwak");?></a></li>
					<li<?php echo ($this->action == 'staff' ? ' class="current"' : '') ?>><a href="/index/staff"><?php echo _t("LBL_MENU_Staff");?></a></li>
					<li<?php echo ($this->action == 'location' ? ' class="current"' : '') ?>><a href="/index/location"><?php echo _t("LBL_MENU_Location and hours");?></a></li>
					<li<?php echo ($this->action == 'contact' ? ' class="current"' : '') ?>><a href="/index/contact"><?php echo _t("LBL_MENU_Contact us");?></a></li>
					<li<?php echo ($this->action == 'faq' ? ' class="current"' : '') ?>><a href="/index/faq"><?php echo _t("LBL_MENU_FAQ");?></a></li>
					<li<?php echo ($this->action == 'insurance' ? ' class="current"' : '') ?>><a href="/index/insurance"><?php echo _t("LBL_MENU_Insurance");?></a></li>
					<li<?php echo ($this->action == 'news' ? ' class="current"' : '') ?>><a href="/index/news"><?php echo _t("LBL_MENU_News");?></a></li>
					<li<?php echo ($this->action == 'links' ? ' class="current"' : '') ?>><a href="/index/links"><?php echo _t("LBL_MENU_Links");?></a></li>
					<li<?php echo ($this->action == 'forms' ? ' class="current"' : '') ?>><a href="/index/forms"><?php echo _t("LBL_MENU_Forms");?></a></li>
				</ul>
                <div class="user-link">
					<a href="https://my.patientfusion.com/"><?php echo _t("LBL_MENU_My Patient Page");?></a>
                </div>
			</div>
            <div class="clr"></div>
            <div class="copyright-block">
                Copyright 2014 by James J. Kwak, M.D. All rights reserved
            </div>
        </div>
    </div>
<script>
    $(document).ready(function () {
        var testimonials = <?php echo json_encode($this->testimonials);?>;
        var currentTestoPage = 0;
        var totalPage = testimonials.length / 2;
        if (testimonials.length % 2 == 1){
            totalPage++;
        }
        $('#testo_more_back').click(function () {
            $( "#testo-list" ).fadeOut( 500, function() {
                changeTestoPage(-1);
            });
        });

        $('#testo_more_next').click(function () {
            $( "#testo-list" ).fadeOut( 500, function() {
                changeTestoPage(1);
            });
        });
        
        function changeTestoPage(changePosition){
            currentTestoPage += changePosition;
            if (currentTestoPage < 0){
                currentTestoPage = totalPage - 1;
            }else if (currentTestoPage >= totalPage){
                currentTestoPage = 0;
            }
            var nOffset = 2 * currentTestoPage;
            var nameObjs = $(".testo-name");
            var textObjs = $(".testo-text");
            nameObjs[0].innerHTML = testimonials[nOffset].name;
            textObjs[0].innerHTML = testimonials[nOffset].text;
            nOffset++;
            if (nOffset >= testimonials.length - 1){
                $('#testo-break').hide();
                $('#testo-detail2').hide();
            }else{
                $('#testo-break').show();
                $('#testo-detail2').show();
                nameObjs[1].innerHTML = testimonials[nOffset].name;
                textObjs[1].innerHTML = testimonials[nOffset].text;
            }
             $( "#testo-list" ).fadeIn(500);
        }
    });
</script>
  </body>
</html>